# Generated by Django 5.2.5 on 2025-10-23 07:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationKYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(max_length=50)),
                ('document_number', models.CharField(max_length=100)),
                ('document_image', models.ImageField(upload_to='kyc_docs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=9)),
                ('rejection_reason', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationRoles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role_name', models.CharField(choices=[('ADMIN', 'Admin'), ('AGENT', 'Agent'), ('RENTER', 'Renter'), ('BUYER', 'Buyer')], max_length=6)),
                ('permissions', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(choices=[('AGENCY', 'Agency'), ('INDEPENDENT_AGENT', 'Independent Agent')], max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('country', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
