# Generated by Django 5.2.5 on 2025-11-10 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='roles',
            field=models.ManyToManyField(related_name='membership_roles', to='organizations.organizationroles'),
        ),
        migrations.AddField(
            model_name='organizationroles',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_organization', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='organizationroles',
            name='permissions',
            field=models.ManyToManyField(related_name='role_permissions', to='organizations.permission'),
        ),
    ]
