# Generated by Django 5.2.5 on 2025-10-23 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationroles',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizations'),
        ),
    ]
